/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Elgammal;


import java.io.BufferedReader;
import java.io.File;
import java.io.FileInputStream;
import java.io.FileNotFoundException;
import java.io.FileOutputStream;
import java.io.FileReader;
import java.io.FileWriter;
import java.io.IOException;
import java.util.ArrayList;
import java.util.Random;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.filechooser.FileFilter;
import javax.swing.filechooser.FileNameExtensionFilter;
//Thu vien ngoai: 
import org.apache.poi.xwpf.extractor.XWPFWordExtractor;
import org.apache.poi.xwpf.usermodel.XWPFDocument;
import org.apache.poi.xwpf.usermodel.XWPFParagraph;
import org.apache.poi.xwpf.usermodel.XWPFRun;

/**
 *
 * @author admin
 */
public class Elgamma extends javax.swing.JFrame {

    /**
     * Creates new form Elgamma
     */

    public Elgamma() {
        initComponents();
    }
    private boolean checkSNT(int n) {
        if (n < 2) {
            return false;
        }
        for (int i = 2; i <= Math.sqrt(n); i++) {
            if (n % i == 0) {
                return false;
            }
        }
        return true;
    }

    private int binhPhuongNhan(int x, int n, int k) {
        int p = 1;
        String s = Integer.toBinaryString(k);
        for (int i = 0; i < s.length(); i++) {
            if (s.charAt(i) == '1') {
                p = p * p;
                p = p % n;
                p = p * x;
                p = p % n;
            } else {
                p = p * p;
                p = p % n;
            }
        }
        return p;
    }

    private int ocolitMoRong(int ri, int ri1) {
        int q[], s[], t[];
        int ri2 = -1, i = 0, n = ri;
        q = new int[100];
        s = new int[100];
        t = new int[100];
        while (ri2 != 0) {
            q[i + 1] = ri / ri1;
            ri2 = ri % ri1;
            switch (i) {
                case 0:
                    s[i] = 1;
                    t[i] = 0;
                    break;
                case 1:
                    s[i] = 0;
                    t[i] = 1;
                    break;
                default:
                    s[i] = s[i - 2] - q[i - 1] * s[i - 1];
                    t[i] = t[i - 2] - q[i - 1] * t[i - 1];
                    break;
            }
            ri = ri1;
            ri1 = ri2;
            i++;
        }
        s[i] = s[i - 2] - q[i - 1] * s[i - 1];
        t[i] = t[i - 2] - q[i - 1] * t[i - 1];
        return t[i] > 0 ? t[i] : (n + t[i]);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        inputP = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        inputAlpha = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        inputA = new javax.swing.JTextField();
        inputBeta = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        inputK = new javax.swing.JTextField();
        taoKey = new javax.swing.JButton();
        Random = new javax.swing.JButton();
        Delete = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        inputBanRo = new javax.swing.JTextArea();
        jLabel9 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        outputBanMa = new javax.swing.JTextArea();
        MaHoa = new javax.swing.JButton();
        Chonfile1 = new javax.swing.JButton();
        Chuyen1 = new javax.swing.JButton();
        LuuFile1 = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();
        Chuyen2 = new javax.swing.JButton();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        inputBanMa = new javax.swing.JTextArea();
        jLabel13 = new javax.swing.JLabel();
        jScrollPane4 = new javax.swing.JScrollPane();
        outputBanRo = new javax.swing.JTextArea();
        GiaiMa = new javax.swing.JButton();
        ChonFile2 = new javax.swing.JButton();
        txtFileMaHoa = new javax.swing.JLabel();
        txtTenFileGiaiMa = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Bài Tập Nhóm Nguyễn Tuấn Kiệt");
        setBackground(new java.awt.Color(102, 102, 102));
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setResizable(false);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setText("MÃ HÓA VÀ GIẢI MÃ ELGAMA");
        jLabel1.setVerticalAlignment(javax.swing.SwingConstants.TOP);

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel2.setText("TẠO KEY");

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel3.setText("p");

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel4.setText("Alpha");

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel5.setText("A");

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel6.setText("Beta");

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel7.setText("K");

        taoKey.setBackground(new java.awt.Color(0, 0, 0));
        taoKey.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        taoKey.setForeground(new java.awt.Color(255, 255, 255));
        taoKey.setText("Tạo key");
        taoKey.setActionCommand("makekey");
        taoKey.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TaoKey(evt);
            }
        });

        Random.setBackground(new java.awt.Color(0, 0, 0));
        Random.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        Random.setForeground(new java.awt.Color(255, 255, 255));
        Random.setText("Random key");
        Random.setActionCommand("randomkey");
        Random.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Random(evt);
            }
        });

        Delete.setBackground(new java.awt.Color(0, 0, 0));
        Delete.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        Delete.setForeground(new java.awt.Color(255, 255, 255));
        Delete.setText("Delete");
        Delete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Xoa(evt);
            }
        });

        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel8.setText("Bản rõ: ");

        inputBanRo.setColumns(20);
        inputBanRo.setLineWrap(true);
        inputBanRo.setRows(5);
        jScrollPane1.setViewportView(inputBanRo);

        jLabel9.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel9.setText("Bản mã:");

        outputBanMa.setColumns(20);
        outputBanMa.setLineWrap(true);
        outputBanMa.setRows(5);
        jScrollPane2.setViewportView(outputBanMa);

        MaHoa.setBackground(new java.awt.Color(0, 0, 0));
        MaHoa.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        MaHoa.setForeground(new java.awt.Color(255, 255, 255));
        MaHoa.setText("Mã Hóa");
        MaHoa.setActionCommand("Mahoa");
        MaHoa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MaHoa(evt);
            }
        });

        Chonfile1.setBackground(new java.awt.Color(0, 0, 0));
        Chonfile1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        Chonfile1.setForeground(new java.awt.Color(255, 255, 255));
        Chonfile1.setText("Chọn file");
        Chonfile1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ChonFile(evt);
            }
        });

        Chuyen1.setBackground(new java.awt.Color(0, 0, 0));
        Chuyen1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        Chuyen1.setForeground(new java.awt.Color(255, 255, 255));
        Chuyen1.setText("Chuyển");
        Chuyen1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Chuyen(evt);
            }
        });

        LuuFile1.setBackground(new java.awt.Color(0, 0, 0));
        LuuFile1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        LuuFile1.setForeground(new java.awt.Color(255, 255, 255));
        LuuFile1.setText("Lưu file");
        LuuFile1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LuuFile(evt);
            }
        });

        jLabel10.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel10.setText("MÃ HÓA");

        Chuyen2.setBackground(new java.awt.Color(0, 0, 0));
        Chuyen2.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        Chuyen2.setForeground(new java.awt.Color(255, 255, 255));
        Chuyen2.setText("Chuyển");
        Chuyen2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Chuyen2(evt);
            }
        });

        jLabel11.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel11.setText("GIẢI MÃ");

        jLabel12.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel12.setText("Bản mã: ");

        inputBanMa.setColumns(20);
        inputBanMa.setLineWrap(true);
        inputBanMa.setRows(5);
        jScrollPane3.setViewportView(inputBanMa);

        jLabel13.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel13.setText("Bản rõ: ");

        outputBanRo.setColumns(20);
        outputBanRo.setLineWrap(true);
        outputBanRo.setRows(5);
        jScrollPane4.setViewportView(outputBanRo);

        GiaiMa.setBackground(new java.awt.Color(0, 0, 0));
        GiaiMa.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        GiaiMa.setForeground(new java.awt.Color(255, 255, 255));
        GiaiMa.setText("Giải mã");
        GiaiMa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                GiaiMa(evt);
            }
        });

        ChonFile2.setBackground(new java.awt.Color(0, 0, 0));
        ChonFile2.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        ChonFile2.setForeground(new java.awt.Color(255, 255, 255));
        ChonFile2.setText("Chọn file");
        ChonFile2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ChonFile2(evt);
            }
        });

        txtFileMaHoa.setText("Tên file");

        txtTenFileGiaiMa.setText("Tên file");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel2)
                            .addComponent(inputP, javax.swing.GroupLayout.DEFAULT_SIZE, 130, Short.MAX_VALUE)
                            .addComponent(inputAlpha)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(inputA))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(taoKey, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(inputBeta)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Delete, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(Random, javax.swing.GroupLayout.DEFAULT_SIZE, 130, Short.MAX_VALUE)
                            .addComponent(inputK))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 103, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(2, 2, 2)
                        .addComponent(jLabel8)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 205, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel10)
                            .addComponent(txtFileMaHoa, javax.swing.GroupLayout.PREFERRED_SIZE, 202, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                            .addGap(54, 54, 54)
                            .addComponent(MaHoa, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(Chonfile1, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(jLabel9)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(Chuyen1, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(LuuFile1, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 205, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 140, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(GiaiMa, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(ChonFile2, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel13)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(Chuyen2, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 205, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(1, 1, 1))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel12)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 205, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel11)
                            .addComponent(txtTenFileGiaiMa, javax.swing.GroupLayout.PREFERRED_SIZE, 204, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(19, 19, 19))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(328, 328, 328))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(inputP, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel8)))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel4)
                            .addComponent(inputAlpha, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(inputA, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(37, 37, 37)
                        .addComponent(taoKey)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel6)
                            .addComponent(inputBeta, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel7)
                            .addComponent(inputK))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(Random)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(Delete))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel10)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(txtFileMaHoa)
                                .addGap(15, 15, 15)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(MaHoa)
                                    .addComponent(Chonfile1))
                                .addGap(40, 40, 40))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(jLabel11)
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel12)
                                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtTenFileGiaiMa)
                                .addGap(15, 15, 15)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(GiaiMa)
                                    .addComponent(ChonFile2))
                                .addGap(43, 43, 43)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel13)
                            .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel9)
                                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(Chuyen1)
                                    .addComponent(Chuyen2)
                                    .addComponent(LuuFile1))))))
                .addGap(53, 53, 53))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void TaoKey(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TaoKey
             int beta;
        if (inputP.getText().isEmpty())
            JOptionPane.showMessageDialog(this, "Vui lòng nhập P!", "Lỗi", JOptionPane.OK_OPTION);
        else if (inputAlpha.getText().isEmpty())
            JOptionPane.showMessageDialog(this, "Vui lòng nhập Alpha!", "Lỗi", JOptionPane.OK_OPTION);
        else if (inputA.getText().isEmpty())
            JOptionPane.showMessageDialog(this, "Vui lòng nhập A!", "Lỗi", JOptionPane.OK_OPTION);
        else {
            
            int p = Integer.valueOf(inputP.getText().trim());
            int alpha = Integer.valueOf(inputAlpha.getText().trim());
            int a = Integer.valueOf(inputA.getText().trim());
           
            if (p < 5000) {
                JOptionPane.showMessageDialog(this, "Vui lòng nhập P>=5000!!!", "Lỗi", JOptionPane.OK_OPTION);
            } else if (!checkSNT(p)) {
                JOptionPane.showMessageDialog(this, "P không phải số nguyên tố. Vui lòng nhập lại!", "Lỗi", JOptionPane.OK_OPTION);
            } else {
                beta = binhPhuongNhan(alpha, p, a);
                inputBeta.setText("" + beta);
                Random rd = new Random();
                int k = rd.nextInt((p - 2) + 1);
                inputK.setText("" + k);
            }
        }
    }//GEN-LAST:event_TaoKey

    private void Xoa(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Xoa
        inputA.setText("");
        inputAlpha.setText("");
        inputBeta.setText("");
        inputP.setText("");
        inputK.setText("");
        inputBanMa.setText("");
        outputBanRo.setText("");
        inputBanRo.setText("");
        outputBanMa.setText("");
        
    }//GEN-LAST:event_Xoa

    private void MaHoa(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MaHoa
         if (inputBanRo.getText().isEmpty())
            JOptionPane.showMessageDialog(this, "Không có thông điệp cần mã hóa!", "Error", JOptionPane.OK_OPTION);
        else {
            if (inputP.getText().isEmpty() || inputAlpha.getText().isEmpty() || inputBeta.getText().isEmpty()) {
                JOptionPane.showMessageDialog(this, "Lỗi tạo khóa!", "Error", JOptionPane.OK_OPTION);
            } else {
                Random random = new Random();
                int p = Integer.valueOf(inputP.getText().trim());
                int alpha = Integer.valueOf(inputAlpha.getText().trim());
                int beta = Integer.valueOf(inputBeta.getText().trim());
                int k = Integer.valueOf(inputK.getText().trim());
                //Tìm y = (y1, y2).
                int y1 = binhPhuongNhan(alpha, p, k);
                int y2;
                String banRo = inputBanRo.getText();
                ArrayList<Integer> arr_ban_ma = new ArrayList<>();
                for (int i = 0; i < banRo.length(); i++) {
                    arr_ban_ma.add(y1);
                    y2 = ((banRo.charAt(i) * binhPhuongNhan(beta, p, k)) % p);
                    arr_ban_ma.add(y2);
                }
                //chuyển chuỗi mã hóa sang dạng chữ:
                String banMa = "";
                for (int j = 0; j < arr_ban_ma.size(); j++) {
                    banMa += (char) (arr_ban_ma.get(j) % p);
                }
                outputBanMa.setText(banMa);
            }
        }
    }//GEN-LAST:event_MaHoa

    private void ChonFile(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ChonFile
                  // TODO add your handling code here:
        JFileChooser jFileChooser = new JFileChooser();
        FileFilter docx = new FileNameExtensionFilter("MS Word file(.docx)", "docx");
        FileFilter txt = new FileNameExtensionFilter("Text file (.txt)", "txt");
        jFileChooser.addChoosableFileFilter(docx);
        jFileChooser.addChoosableFileFilter(txt);
        int respone = jFileChooser.showOpenDialog(null);
        if (respone == JFileChooser.APPROVE_OPTION) {
            File file = new File(jFileChooser.getSelectedFile().getAbsolutePath());
            txtFileMaHoa.setText(file.getPath());
            if(file.getName().endsWith(".docx")){
            try {
                XWPFDocument document =new XWPFDocument(new FileInputStream(file));
                XWPFWordExtractor word = new XWPFWordExtractor(document);
                inputBanRo.setText(word.getText());
            } catch (IOException ex) {
                Logger.getLogger(Elgamma.class.getName()).log(Level.SEVERE, null, ex);
            }   }
            else if(file.getName().endsWith(".txt"))
            {
             BufferedReader reader;
		try {
			reader = new BufferedReader(new FileReader(file));
			String line = reader.readLine();
                        String g="";
			while (line != null) {
				g=g+line+"\n";
				line = reader.readLine();
			}
                       inputBanRo.setText(g);
		       reader.close();
		} catch (IOException e) {
		}
            }
        }
    }//GEN-LAST:event_ChonFile

    private void Chuyen(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Chuyen
        // TODO add your handling code here:
         if (outputBanMa.getText().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Không có bản mã để gửi đi!", "Error", JOptionPane.ERROR_MESSAGE);
        } else
            inputBanMa.setText(outputBanMa.getText());
    }//GEN-LAST:event_Chuyen

    private void LuuFile(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LuuFile
        // TODO add your handling code here:
        JFileChooser jFileChooser = new JFileChooser();
        jFileChooser.showSaveDialog(null);
        File file = jFileChooser.getSelectedFile();
        if(file.getName().endsWith(".docx")){
        XWPFDocument document =new XWPFDocument();
        XWPFParagraph para=document.createParagraph();
        XWPFRun run=para.createRun();
              try {
                  run.setText(outputBanMa.getText());
                  FileOutputStream out=new FileOutputStream(file);
                  document.write(out);
              } catch (FileNotFoundException ex) {
                  Logger.getLogger(Elgamma.class.getName()).log(Level.SEVERE, null, ex);
              } catch (IOException ex) {
                  Logger.getLogger(Elgamma.class.getName()).log(Level.SEVERE, null, ex);
              }
        
        }
        else if (file.getName().endsWith(".txt")){
            try {
            try (FileWriter fileWriter = new FileWriter(file)) {
                fileWriter.write(outputBanMa.getText());
            }
        } catch (IOException ex) {
            System.out.println(ex.getMessage());
        }
        }
    }//GEN-LAST:event_LuuFile

    private void GiaiMa(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_GiaiMa
        // TODO add your handling code here:
          if (inputBanMa.getText().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Không có thông điệp cần giải mã!", "Error", JOptionPane.ERROR_MESSAGE);
        } else {
            ArrayList<Integer> arr_ban_ma = new ArrayList<>();
            String banMa = inputBanMa.getText();
            int p = Integer.parseInt(inputP.getText().trim());
            int a = Integer.parseInt(inputA.getText().trim());
            for (int i = 0; i < banMa.length(); i++) {
                arr_ban_ma.add((int) banMa.charAt(i));
            }
            //d=y2(y1^a)^-1 mod p
            int k = binhPhuongNhan(arr_ban_ma.get(0), p, a);  //k=y1^a mod p
            String banRo = "";
            for (int j = 1; j < arr_ban_ma.size(); j += 2) {
                //d=y2(k)^-1 mod p
                char c = (char) ((arr_ban_ma.get(j) * ocolitMoRong(p, k)) % p);
                banRo += c;
            }
            outputBanRo.setText(banRo);
        }
    }//GEN-LAST:event_GiaiMa

    private void ChonFile2(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ChonFile2
        // TODO add your handling code here:
        JFileChooser jFileChooser = new JFileChooser();
        int respone = jFileChooser.showOpenDialog(null);
        FileFilter docx = new FileNameExtensionFilter("MS Word file(.docx)", "docx");
        FileFilter txt = new FileNameExtensionFilter("Text file (.txt)", "txt");
        jFileChooser.addChoosableFileFilter(docx);
        jFileChooser.addChoosableFileFilter(txt);
        if (respone == JFileChooser.APPROVE_OPTION) {
            File file = new File(jFileChooser.getSelectedFile().getAbsolutePath());
            txtTenFileGiaiMa.setText(file.getName());
            if(file.getName().endsWith(".docx")){
            try {
                XWPFDocument document =new XWPFDocument(new FileInputStream(file));
                XWPFWordExtractor word = new XWPFWordExtractor(document);
                inputBanMa.setText(word.getText());
            } catch (IOException ex) {
                Logger.getLogger(Elgamma.class.getName()).log(Level.SEVERE, null, ex);
            }   }
            else if(file.getName().endsWith(".txt"))
            {
                BufferedReader reader;
		try {
			reader = new BufferedReader(new FileReader(file));
			String line = reader.readLine();
                        String g="";
			while (line != null) {
				g=g+line+"\n";
				line = reader.readLine();
			}
                       inputBanMa.setText(g);
			reader.close();
		} catch (IOException e) {
			
		}
        }    }   
    }//GEN-LAST:event_ChonFile2

    private void Random(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Random
            int max = 45000, min = 8000;
        int p, a, alpha, beta, k;
        Random random = new Random();
        do {
            p = random.nextInt((max - min) + 1) + min;
        } while (checkSNT(p) == false);
        inputP.setText("" + p);
        //set a
        a = random.nextInt((p - 2) + 1) + 2;
        inputA.setText("" + a);
        //set alpha 
        alpha = random.nextInt((p - 1) + 1) + 1;
        inputAlpha.setText("" + alpha);
        //set K
        k = random.nextInt((p - 2) + 1);
        inputK.setText("" + k);
        //set beta 
        beta = binhPhuongNhan(alpha, p, a);
        inputBeta.setText("" + beta);
    }//GEN-LAST:event_Random

    private void Chuyen2(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Chuyen2
        // TODO add your handling code here:
        if (outputBanRo.getText().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Không có bản rõ để gửi đi!", "Error", JOptionPane.ERROR_MESSAGE);
        } else
        inputBanRo.setText(outputBanRo.getText());
    }//GEN-LAST:event_Chuyen2

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Elgamma.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Elgamma.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Elgamma.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Elgamma.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new Elgamma().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ChonFile2;
    private javax.swing.JButton Chonfile1;
    private javax.swing.JButton Chuyen1;
    private javax.swing.JButton Chuyen2;
    private javax.swing.JButton Delete;
    private javax.swing.JButton GiaiMa;
    private javax.swing.JButton LuuFile1;
    private javax.swing.JButton MaHoa;
    private javax.swing.JButton Random;
    private javax.swing.JTextField inputA;
    private javax.swing.JTextField inputAlpha;
    private javax.swing.JTextArea inputBanMa;
    private javax.swing.JTextArea inputBanRo;
    private javax.swing.JTextField inputBeta;
    private javax.swing.JTextField inputK;
    private javax.swing.JTextField inputP;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JTextArea outputBanMa;
    private javax.swing.JTextArea outputBanRo;
    private javax.swing.JButton taoKey;
    private javax.swing.JLabel txtFileMaHoa;
    private javax.swing.JLabel txtTenFileGiaiMa;
    // End of variables declaration//GEN-END:variables
}
